package signify

import (
	"bytes"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// Fixtures come from the real toolchain: keys generated by gosignify -G, and
// recipe.yaml with its signature fetched from plakar.io. These tests therefore
// fail if this package ever stops agreeing with signify(1) itself.
const fixturePassphrase = "hunter2"

func fixture(t *testing.T, name string) []byte {
	t.Helper()

	data, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatalf("reading fixture %s: %v", name, err)
	}

	return data
}

func testKeyPair(t *testing.T) (*PublicKey, *SecretKey) {
	t.Helper()

	pk, err := ParsePublicKey(fixture(t, "testkey.pub"))
	if err != nil {
		t.Fatalf("ParsePublicKey: %v", err)
	}

	sk, err := ParseSecretKey(fixture(t, "testkey.sec"), []byte(fixturePassphrase))
	if err != nil {
		t.Fatalf("ParseSecretKey: %v", err)
	}

	return pk, sk
}

func TestParsePublicKey(t *testing.T) {
	pk, err := ParsePublicKey(fixture(t, "testkey.pub"))
	if err != nil {
		t.Fatalf("ParsePublicKey: %v", err)
	}

	if len(pk.Key) != 32 {
		t.Errorf("key is %d bytes, want 32", len(pk.Key))
	}

	if pk.Comment == "" {
		t.Error("expected a comment")
	}
}

func TestPublicKeyRoundTrip(t *testing.T) {
	original := fixture(t, "testkey.pub")

	pk, err := ParsePublicKey(original)
	if err != nil {
		t.Fatal(err)
	}

	out, err := pk.Marshal()
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(out, original) {
		t.Errorf("round trip changed the file:\n got %q\nwant %q", out, original)
	}
}

func TestParseSecretKey(t *testing.T) {
	sk, err := ParseSecretKey(fixture(t, "testkey.sec"), []byte(fixturePassphrase))
	if err != nil {
		t.Fatalf("ParseSecretKey: %v", err)
	}

	if !sk.Encrypted() {
		t.Error("fixture key should be passphrase-protected")
	}

	pk, _ := ParsePublicKey(fixture(t, "testkey.pub"))
	if sk.KeyNum != pk.KeyNum {
		t.Error("secret and public key numbers differ")
	}

	if !bytes.Equal(sk.Public().Key, pk.Key) {
		t.Error("derived public key does not match the published one")
	}
}

// A wrong passphrase must be an error, not a key that signs garbage.
func TestParseSecretKeyWrongPassphrase(t *testing.T) {
	for _, pass := range []string{"", "wrong", "hunter3"} {
		_, err := ParseSecretKey(fixture(t, "testkey.sec"), []byte(pass))
		if !errors.Is(err, ErrWrongPassphrase) {
			t.Errorf("passphrase %q: got %v, want ErrWrongPassphrase", pass, err)
		}
	}
}

func TestSecretKeyRoundTrip(t *testing.T) {
	original := fixture(t, "testkey.sec")

	sk, err := ParseSecretKey(original, []byte(fixturePassphrase))
	if err != nil {
		t.Fatal(err)
	}

	out, err := sk.Marshal([]byte(fixturePassphrase))
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(out, original) {
		t.Error("re-encrypting the key did not reproduce the original file")
	}
}

func TestGenerateKeyAndSign(t *testing.T) {
	pk, sk, err := GenerateKey("test key")
	if err != nil {
		t.Fatal(err)
	}

	if pk.KeyNum != sk.KeyNum {
		t.Error("generated keys have different key numbers")
	}

	msg := []byte("the message")

	sig := sk.Sign(msg, SignatureComment("test"))
	if err := pk.Verify(msg, sig); err != nil {
		t.Errorf("freshly signed message failed to verify: %v", err)
	}

	if sig.Comment != "verify with test.pub" {
		t.Errorf("comment = %q", sig.Comment)
	}
}

// Two generated keys must not collide, or key selection by number breaks.
func TestGenerateKeyIsUnique(t *testing.T) {
	a, _, err := GenerateKey("a")
	if err != nil {
		t.Fatal(err)
	}

	b, _, err := GenerateKey("b")
	if err != nil {
		t.Fatal(err)
	}

	if a.KeyNum == b.KeyNum {
		t.Error("two generated keys share a key number")
	}
}

func TestUnencryptedSecretKey(t *testing.T) {
	_, sk, err := GenerateKey("unattended")
	if err != nil {
		t.Fatal(err)
	}

	data, err := sk.Marshal(nil)
	if err != nil {
		t.Fatal(err)
	}

	// An unencrypted key must load with no passphrase, which is what
	// makes unattended signing possible.
	got, err := ParseSecretKey(data, nil)
	if err != nil {
		t.Fatalf("ParseSecretKey on an unencrypted key: %v", err)
	}

	if got.Encrypted() {
		t.Error("key reports as encrypted")
	}

	if !bytes.Equal(got.Key, sk.Key) {
		t.Error("round trip changed the key")
	}
}

// distKey is the live PlakarKorp signing key, which produced the published
// fixtures. Distinct from testkey, which only exercises round trips.
func distKey(t *testing.T) *PublicKey {
	t.Helper()

	pk, err := ParsePublicKey(fixture(t, "plakar-dist.pub"))
	if err != nil {
		t.Fatalf("ParsePublicKey: %v", err)
	}

	return pk
}

// The embedded signature published on plakar.io must verify here.
func TestVerifyRealEmbeddedSignature(t *testing.T) {
	pk := distKey(t)

	sig, err := ParseSignature(fixture(t, "recipe.yaml.sum.sig"))
	if err != nil {
		t.Fatalf("ParseSignature: %v", err)
	}

	if !sig.Embedded() {
		t.Fatal("published signature should be embedded")
	}

	msg, err := pk.VerifyEmbedded(sig)
	if err != nil {
		t.Fatalf("published signature failed to verify: %v", err)
	}

	if !bytes.Equal(msg, fixture(t, "recipe.yaml.sum")) {
		t.Error("embedded message differs from the published .sum")
	}
}

func TestSignatureRoundTrip(t *testing.T) {
	original := fixture(t, "recipe.yaml.sum.sig")

	sig, err := ParseSignature(original)
	if err != nil {
		t.Fatal(err)
	}

	out, err := sig.Marshal()
	if err != nil {
		t.Fatal(err)
	}

	if !bytes.Equal(out, original) {
		t.Errorf("round trip changed the signature file")
	}
}

func TestSignEmbedded(t *testing.T) {
	pk, sk := testKeyPair(t)

	msg := []byte("SHA256 (x.ptar) = " + strings.Repeat("a", 64) + "\n")

	sig := sk.SignEmbedded(msg, SignatureComment("plakar-20260815"))

	data, err := sig.Marshal()
	if err != nil {
		t.Fatal(err)
	}

	parsed, err := ParseSignature(data)
	if err != nil {
		t.Fatal(err)
	}

	got, err := pk.VerifyEmbedded(parsed)
	if err != nil {
		t.Fatalf("verify: %v", err)
	}

	if !bytes.Equal(got, msg) {
		t.Error("embedded message did not survive the round trip")
	}
}

func TestVerifyRejectsTamperedMessage(t *testing.T) {
	pk := distKey(t)

	sig, err := ParseSignature(fixture(t, "recipe.yaml.sum.sig"))
	if err != nil {
		t.Fatal(err)
	}

	tampered := bytes.Replace(sig.Message, []byte("745862"), []byte("000000"), 1)

	if err := pk.Verify(tampered, sig); !errors.Is(err, ErrBadSignature) {
		t.Errorf("got %v, want ErrBadSignature", err)
	}
}

// A different key must be reported as a mismatch, not a bad signature: the
// two mean different things to a caller choosing among several trusted keys.
func TestVerifyRejectsWrongKey(t *testing.T) {
	other, err := ParsePublicKey(fixture(t, "other.pub"))
	if err != nil {
		t.Fatal(err)
	}

	sig, err := ParseSignature(fixture(t, "recipe.yaml.sum.sig"))
	if err != nil {
		t.Fatal(err)
	}

	if err := other.Verify(sig.Message, sig); !errors.Is(err, ErrKeyMismatch) {
		t.Errorf("got %v, want ErrKeyMismatch", err)
	}
}

func TestVerifyEmbeddedRejectsDetached(t *testing.T) {
	pk, sk := testKeyPair(t)

	sig := sk.Sign([]byte("msg"), "c")

	if _, err := pk.VerifyEmbedded(sig); !errors.Is(err, ErrInvalidFormat) {
		t.Errorf("got %v, want ErrInvalidFormat", err)
	}
}

func TestDetachedSignatureHasNoMessage(t *testing.T) {
	lines := strings.SplitN(string(fixture(t, "recipe.yaml.sum.sig")), "\n", 3)
	detached := []byte(lines[0] + "\n" + lines[1] + "\n")

	sig, err := ParseSignature(detached)
	if err != nil {
		t.Fatal(err)
	}

	if sig.Embedded() {
		t.Error("expected a detached signature")
	}

	if err := distKey(t).Verify(fixture(t, "recipe.yaml.sum"), sig); err != nil {
		t.Errorf("detached signature failed to verify: %v", err)
	}
}

func TestParseRejectsMalformed(t *testing.T) {
	valid := fixture(t, "recipe.yaml.sum.sig")

	cases := []struct {
		name string
		data []byte
		want error
	}{
		{"empty", nil, ErrInvalidFormat},
		{"no header", []byte("hello\nworld\n"), ErrInvalidFormat},
		{"one line", []byte(commentHdr + "x"), ErrInvalidFormat},
		{"bad base64", []byte(commentHdr + "x\n!!!\n"), ErrInvalidFormat},
		{"short payload", []byte(commentHdr + "x\nRWQ=\n"), ErrInvalidFormat},
		{"wrong algorithm", []byte(commentHdr + "x\nWFgAAAAAAAAAAA==\n"), ErrUnsupportedAlgorithm},
		{"signature as key", valid, ErrInvalidFormat},
		{"long comment", []byte(commentHdr + strings.Repeat("x", MaxCommentLen) + "\nRWQ=\n"), ErrCommentTooLong},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if _, err := ParsePublicKey(tc.data); !errors.Is(err, tc.want) {
				t.Errorf("ParsePublicKey: got %v, want %v", err, tc.want)
			}
		})
	}
}

func TestParseSignatureRejectsPublicKey(t *testing.T) {
	if _, err := ParseSignature(fixture(t, "testkey.pub")); !errors.Is(err, ErrInvalidFormat) {
		t.Errorf("got %v, want ErrInvalidFormat", err)
	}
}

func TestParseSecretKeyRejectsPublicKey(t *testing.T) {
	if _, err := ParseSecretKey(fixture(t, "testkey.pub"), nil); !errors.Is(err, ErrInvalidFormat) {
		t.Errorf("got %v, want ErrInvalidFormat", err)
	}
}

func TestMarshalRejectsLongComment(t *testing.T) {
	pk, _ := testKeyPair(t)
	pk.Comment = strings.Repeat("x", MaxCommentLen)

	if _, err := pk.Marshal(); !errors.Is(err, ErrCommentTooLong) {
		t.Errorf("got %v, want ErrCommentTooLong", err)
	}
}

func TestKeyNumString(t *testing.T) {
	pk, _ := testKeyPair(t)

	if pk.KeyNum.String() == "" {
		t.Error("expected a printable key number")
	}
}

// SignatureComment must take a bare name: signify(1) derives it from the path
// it was given, which publishes the signing host's layout in every signature.
func TestSignatureCommentUsesBareName(t *testing.T) {
	if got := SignatureComment("plakar-20260815"); got != "verify with plakar-20260815.pub" {
		t.Errorf("got %q", got)
	}
}
